### ISSUE TITLE
Install via npm fails with unmetgrunt  dependency

### ISSUE THREAD

**Issue by dvatp** [vsn4ik/bootstrap-checkbox#28]
Attempting to install bootstrap-checkbox via npm fails with:

/home/dvatp
├── bootstrap-checkbox@1.4.0 
└── UNMET PEER DEPENDENCY grunt@~0.4.5
npm WARN bootstrap-checkbox@1.4.0 requires a peer of grunt@~0.4.5 but none was installed.

So it's looking for grunt 0.4.5 but that is apparently no longer available in the repository so the dependency can't be satisfied.

This is odd because I checked the source for 1.4.0 and package.json indicates a dependency on a 1.x variant of grunt.  Was the package built incorrectly?

**Comment by vsn4ik** [comment]
Fixed in `v1.5.0`
