### ISSUE TITLE
Bootstrap 4 compitibility

### ISSUE THREAD

**Issue by snimavat** [vsn4ik/bootstrap-checkbox#33]
Is there any time frame to make the project compitible with latest bootstrap 4 .

**Comment by vsn4ik** [comment]
Full compitibility in `v.1.5.0` with
```js
$(':checkbox').checkboxpicker({
  offCls: 'btn-secondary',
  onCls: 'btn-secondary',
  ...
});

**Comment by SlyDave** [comment]
Took me ages to find this. Might want to add it into the docs ! Thanks for your hard work.
