### ISSUE TITLE
New logo for bootstrap-checkbox

### ISSUE THREAD

**Issue by reallinfo** [vsn4ik/bootstrap-checkbox#36]
I wanted to contribute to bootstrap-checkbox. I designed a logo for it. If you like it, I'll send you files and pr.
is there anything you want?

![bcheck](https://user-images.githubusercontent.com/36298335/38277306-a07e8e72-37a0-11e8-8a70-f48aeab88bc9.jpg)

**Comment by vsn4ik** [comment]
This is awesome!

**Comment by reallinfo** [comment]
Thanks! I sent pr. Please check it.

https://github.com/vsn4ik/bootstrap-checkbox/pull/37

**Comment by vsn4ik** [comment]
Merged.
Thanks @reallinfo!
